# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstaScanReactNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'KaizenTestFramework', :path => 'KaizenTestFramework'

  # Pods for InstaScanReactNative

end
