# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'InstaScanReactNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'InstaScan', :git => 'https://bitbucket.org/kaizentelekom/instascanios.git'

  # Pods for InstaScanReactNative

end
